#!/usr/bin/env python3
"""
Translates the EMIT_WRITE/EMIT_MASKWRITE/EMIT_MASKPOLL register writes in
tools/zybo_z7_20_bsp/ps7_init.c into OpenOCD Tcl procs, so the JTAG
debug-run flow (tools/jtag_run.sh) uses the exact same authoritative
Zybo Z7-20 register data as the FSBL, instead of a separately
hand-transcribed copy that could drift out of sync.

DDR init is intentionally not translated: the JTAG flow only runs plain
OCM-resident apps (same as the NODDR FSBL used for SD/QSPI boot), so it's
not needed, same as ps7_init.c's own stubbed-out ps7_ddr_init_data_3_0.
"""
import re
import sys

def extract(src, name):
    pat = re.compile(r'unsigned long ' + name + r'\[\] = \{(.*?)\n\};', re.S)
    m = pat.search(src)
    if not m:
        raise SystemExit(f"couldn't find {name}")
    return m.group(1)

def clean_num(tok):
    return tok.strip().rstrip('Uu')

def to_tcl_proc(body, procname):
    lines = [f'proc {procname} {{}} {{']
    for m in re.finditer(r'EMIT_(WRITE|MASKWRITE|MASKPOLL|MASKDELAY|EXIT)\(([^)]*)\)', body):
        op, args = m.group(1), m.group(2)
        parts = [clean_num(a) for a in args.split(',')] if args.strip() else []
        if op == 'WRITE':
            addr, val = parts
            lines.append(f'    mww {addr} {val}')
        elif op == 'MASKWRITE':
            addr, mask, val = parts
            lines.append(f'    maskwrite {addr} {mask} {val}')
        elif op == 'MASKPOLL':
            addr, mask = parts
            lines.append(f'    maskpoll {addr} {mask}')
        elif op == 'MASKDELAY':
            lines.append(f'    # skip: timer-based delay, not needed via JTAG halt')
        elif op == 'EXIT':
            pass
    lines.append('}')
    return '\n'.join(lines)

def main():
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} ps7_init.c")
    src = open(sys.argv[1]).read()

    print('# Generated by tools/gen_ps7_init_tcl.py -- do not hand-edit.')
    print('# Same register semantics as ps7_config() in ps7_init.c: MASKWRITE')
    print('# preserves bits outside mask, MASKPOLL waits until (val & mask) != 0.')
    print()
    print('proc rdw {addr} {')
    print('    return [lindex [read_memory $addr 32 1] 0]')
    print('}')
    print()
    print('proc maskwrite {addr mask val} {')
    print('    set cur [rdw $addr]')
    print('    set new [expr {($cur & ~($mask)) | ($val & $mask)}]')
    print('    mww $addr $new')
    print('}')
    print()
    print('proc maskpoll {addr mask} {')
    print('    set i 0')
    print('    while {$i < 200000} {')
    print('        set val [rdw $addr]')
    print('        if {($val & $mask) != 0} { return }')
    print('        incr i')
    print('    }')
    print('    echo "WARNING: maskpoll timeout at $addr (mask $mask)"')
    print('}')
    print()

    for arr, proc in [
        ('ps7_mio_init_data_3_0', 'ps7_mio_init'),
        ('ps7_pll_init_data_3_0', 'ps7_pll_init'),
        ('ps7_clock_init_data_3_0', 'ps7_clock_init'),
        ('ps7_peripherals_init_data_3_0', 'ps7_peripherals_init'),
        ('ps7_post_config_3_0', 'ps7_post_config'),
    ]:
        print(to_tcl_proc(extract(src, arr), proc))
        print()

    print('# MIO -> PLL -> clock -> peripherals, matching ps7_init()\'s own')
    print('# order (DDR step omitted -- see module docstring).')
    print('proc ps7_mio_pll_clock_init {} {')
    print('    ps7_mio_init')
    print('    ps7_pll_init')
    print('    ps7_clock_init')
    print('    ps7_peripherals_init')
    print('}')

if __name__ == '__main__':
    main()
