/******************************************************************************
* Copyright (c) 2010 - 2020 Xilinx, Inc. All rights reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/

/****************************************************************************/
/**
*
* @file ps7_init.c
*
* This file is automatically generated
*
*****************************************************************************/

#include "ps7_init.h"

#define PS7_MASK_POLL_TIME 100000000

char*
getPS7MessageInfo(unsigned key) {

  char* err_msg = "";
  switch (key) {
	case PS7_INIT_SUCCESS:                  err_msg = "PS7 initialization successful"; break;
	case PS7_INIT_CORRUPT:                  err_msg = "PS7 init Data Corrupted"; break;
	case PS7_INIT_TIMEOUT:                  err_msg = "PS7 init mask poll timeout"; break;
	case PS7_POLL_FAILED_DDR_INIT:          err_msg = "Mask Poll failed for DDR Init"; break;
	case PS7_POLL_FAILED_DMA:               err_msg = "Mask Poll failed for PLL Init"; break;
	case PS7_POLL_FAILED_PLL:               err_msg = "Mask Poll failed for DMA done bit"; break;
	default:                                err_msg = "Undefined error status"; break;
  }

  return err_msg;
}

unsigned long ps7_pll_init_data_3_0[] = {
	EMIT_WRITE(0xF8000008, 0x0000DF0DU),
	EMIT_MASKWRITE(0xF8000110, 0x003FFFF0U, 0x000FA220U),
	EMIT_MASKWRITE(0xF8000100, 0x0007F000U, 0x00028000U),
	EMIT_MASKWRITE(0xF8000100, 0x00000010U, 0x00000010U),
	EMIT_MASKWRITE(0xF8000100, 0x00000001U, 0x00000001U),
	EMIT_MASKWRITE(0xF8000100, 0x00000001U, 0x00000000U),
	EMIT_MASKPOLL(0xF800010C, 0x00000001U),
	EMIT_MASKWRITE(0xF8000100, 0x00000010U, 0x00000000U),
	EMIT_MASKWRITE(0xF8000120, 0x1F003F30U, 0x1F000200U),
	EMIT_MASKWRITE(0xF8000114, 0x003FFFF0U, 0x0012C220U),
	EMIT_MASKWRITE(0xF8000104, 0x0007F000U, 0x00020000U),
	EMIT_MASKWRITE(0xF8000104, 0x00000010U, 0x00000010U),
	EMIT_MASKWRITE(0xF8000104, 0x00000001U, 0x00000001U),
	EMIT_MASKWRITE(0xF8000104, 0x00000001U, 0x00000000U),
	EMIT_MASKPOLL(0xF800010C, 0x00000002U),
	EMIT_MASKWRITE(0xF8000104, 0x00000010U, 0x00000000U),
	EMIT_MASKWRITE(0xF8000124, 0xFFF00003U, 0x0C200003U),
	EMIT_MASKWRITE(0xF8000118, 0x003FFFF0U, 0x001452C0U),
	EMIT_MASKWRITE(0xF8000108, 0x0007F000U, 0x0001E000U),
	EMIT_MASKWRITE(0xF8000108, 0x00000010U, 0x00000010U),
	EMIT_MASKWRITE(0xF8000108, 0x00000001U, 0x00000001U),
	EMIT_MASKWRITE(0xF8000108, 0x00000001U, 0x00000000U),
	EMIT_MASKPOLL(0xF800010C, 0x00000004U),
	EMIT_MASKWRITE(0xF8000108, 0x00000010U, 0x00000000U),
	EMIT_WRITE(0xF8000004, 0x0000767BU),
	EMIT_EXIT(),
};

unsigned long ps7_clock_init_data_3_0[] = {
	EMIT_WRITE(0xF8000008, 0x0000DF0DU),
	EMIT_MASKWRITE(0xF8000128, 0x03F03F01U, 0x00700F01U),
	EMIT_MASKWRITE(0xF8000138, 0x00000011U, 0x00000001U),
	EMIT_MASKWRITE(0xF8000140, 0x03F03F71U, 0x00100801U),
	EMIT_MASKWRITE(0xF800014C, 0x00003F31U, 0x00000501U),
	EMIT_MASKWRITE(0xF8000150, 0x00003F33U, 0x00001401U),
	EMIT_MASKWRITE(0xF8000154, 0x00003F33U, 0x00000A02U),
	EMIT_MASKWRITE(0xF8000168, 0x00003F31U, 0x00000501U),
	EMIT_MASKWRITE(0xF8000170, 0x03F03F30U, 0x00400500U),
	EMIT_MASKWRITE(0xF80001C4, 0x00000001U, 0x00000001U),
	EMIT_MASKWRITE(0xF800012C, 0x01FFCCCDU, 0x01EC044DU),
	EMIT_WRITE(0xF8000004, 0x0000767BU),
	EMIT_EXIT(),
};

unsigned long ps7_ddr_init_data_3_0[] = {
	// This design uses no DDR (NODDR build) -- see comment above ps7_init().
	EMIT_EXIT(),
};

unsigned long ps7_mio_init_data_3_0[] = {
	EMIT_WRITE(0xF8000008, 0x0000DF0DU),
	EMIT_MASKWRITE(0xF8000B40, 0x00000FFFU, 0x00000600U),
	EMIT_MASKWRITE(0xF8000B44, 0x00000FFFU, 0x00000600U),
	EMIT_MASKWRITE(0xF8000B48, 0x00000FFFU, 0x00000672U),
	EMIT_MASKWRITE(0xF8000B4C, 0x00000FFFU, 0x00000672U),
	EMIT_MASKWRITE(0xF8000B50, 0x00000FFFU, 0x00000674U),
	EMIT_MASKWRITE(0xF8000B54, 0x00000FFFU, 0x00000674U),
	EMIT_MASKWRITE(0xF8000B58, 0x00000FFFU, 0x00000600U),
	EMIT_MASKWRITE(0xF8000B5C, 0xFFFFFFFFU, 0x0018C068U),
	EMIT_MASKWRITE(0xF8000B60, 0xFFFFFFFFU, 0x00F98068U),
	EMIT_MASKWRITE(0xF8000B64, 0xFFFFFFFFU, 0x00F98068U),
	EMIT_MASKWRITE(0xF8000B68, 0xFFFFFFFFU, 0x00F98068U),
	EMIT_MASKWRITE(0xF8000B6C, 0x00007FFFU, 0x00000260U),
	EMIT_MASKWRITE(0xF8000B70, 0x00000001U, 0x00000001U),
	EMIT_MASKWRITE(0xF8000B70, 0x00000021U, 0x00000020U),
	EMIT_MASKWRITE(0xF8000B70, 0x07FEFFFFU, 0x00000823U),
	EMIT_MASKWRITE(0xF8000700, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF8000704, 0x00003FFFU, 0x00001602U),
	EMIT_MASKWRITE(0xF8000708, 0x00003FFFU, 0x00000602U),
	EMIT_MASKWRITE(0xF800070C, 0x00003FFFU, 0x00000602U),
	EMIT_MASKWRITE(0xF8000710, 0x00003FFFU, 0x00000602U),
	EMIT_MASKWRITE(0xF8000714, 0x00003FFFU, 0x00000602U),
	EMIT_MASKWRITE(0xF8000718, 0x00003FFFU, 0x00000602U),
	EMIT_MASKWRITE(0xF800071C, 0x00003FFFU, 0x00000600U),
	EMIT_MASKWRITE(0xF8000720, 0x00003FFFU, 0x00000602U),
	EMIT_MASKWRITE(0xF8000724, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF8000728, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF800072C, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF8000730, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF8000734, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF8000738, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF800073C, 0x00003FFFU, 0x00001600U),
	EMIT_MASKWRITE(0xF8000740, 0x00003FFFU, 0x00001302U),
	EMIT_MASKWRITE(0xF8000744, 0x00003FFFU, 0x00001302U),
	EMIT_MASKWRITE(0xF8000748, 0x00003FFFU, 0x00001302U),
	EMIT_MASKWRITE(0xF800074C, 0x00003FFFU, 0x00001302U),
	EMIT_MASKWRITE(0xF8000750, 0x00003FFFU, 0x00001302U),
	EMIT_MASKWRITE(0xF8000754, 0x00003FFFU, 0x00001302U),
	EMIT_MASKWRITE(0xF8000758, 0x00003FFFU, 0x00001303U),
	EMIT_MASKWRITE(0xF800075C, 0x00003FFFU, 0x00001303U),
	EMIT_MASKWRITE(0xF8000760, 0x00003FFFU, 0x00001303U),
	EMIT_MASKWRITE(0xF8000764, 0x00003FFFU, 0x00001303U),
	EMIT_MASKWRITE(0xF8000768, 0x00003FFFU, 0x00001303U),
	EMIT_MASKWRITE(0xF800076C, 0x00003FFFU, 0x00001303U),
	EMIT_MASKWRITE(0xF8000770, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF8000774, 0x00003FFFU, 0x00001305U),
	EMIT_MASKWRITE(0xF8000778, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF800077C, 0x00003FFFU, 0x00001305U),
	EMIT_MASKWRITE(0xF8000780, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF8000784, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF8000788, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF800078C, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF8000790, 0x00003FFFU, 0x00001305U),
	EMIT_MASKWRITE(0xF8000794, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF8000798, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF800079C, 0x00003FFFU, 0x00001304U),
	EMIT_MASKWRITE(0xF80007A0, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF80007A4, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF80007A8, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF80007AC, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF80007B0, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF80007B4, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF80007B8, 0x00003FFFU, 0x00001200U),
	EMIT_MASKWRITE(0xF80007BC, 0x00003F01U, 0x00001201U),
	EMIT_MASKWRITE(0xF80007C0, 0x00003FFFU, 0x000012E0U),
	EMIT_MASKWRITE(0xF80007C4, 0x00003FFFU, 0x000012E1U),
	EMIT_MASKWRITE(0xF80007C8, 0x00003FFFU, 0x00001200U),
	EMIT_MASKWRITE(0xF80007CC, 0x00003FFFU, 0x00001200U),
	EMIT_MASKWRITE(0xF80007D0, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF80007D4, 0x00003FFFU, 0x00001280U),
	EMIT_MASKWRITE(0xF8000830, 0x003F003FU, 0x002F0037U),
	EMIT_WRITE(0xF8000004, 0x0000767BU),
	EMIT_EXIT(),
};

unsigned long ps7_peripherals_init_data_3_0[] = {
	EMIT_WRITE(0xF8000008, 0x0000DF0DU),
	EMIT_MASKWRITE(0xF8000B48, 0x00000180U, 0x00000180U),
	EMIT_MASKWRITE(0xF8000B4C, 0x00000180U, 0x00000180U),
	EMIT_MASKWRITE(0xF8000B50, 0x00000180U, 0x00000180U),
	EMIT_MASKWRITE(0xF8000B54, 0x00000180U, 0x00000180U),
	EMIT_WRITE(0xF8000004, 0x0000767BU),
	EMIT_MASKWRITE(0xE0001034, 0x000000FFU, 0x00000006U),
	EMIT_MASKWRITE(0xE0001018, 0x0000FFFFU, 0x0000007CU),
	EMIT_MASKWRITE(0xE0001000, 0x000001FFU, 0x00000017U),
	EMIT_MASKWRITE(0xE0001004, 0x000003FFU, 0x00000020U),
	EMIT_MASKWRITE(0xE000D000, 0x00080000U, 0x00080000U),
	EMIT_MASKWRITE(0xF8007000, 0x20000000U, 0x00000000U),
	EMIT_MASKWRITE(0xE000A244, 0x003FFFFFU, 0x00004000U),
	EMIT_MASKWRITE(0xE000A008, 0xFFFFFFFFU, 0xBFFF4000U),
	EMIT_MASKWRITE(0xE000A248, 0x003FFFFFU, 0x00004000U),
	EMIT_MASKWRITE(0xE000A008, 0xFFFFFFFFU, 0xBFFF0000U),
	EMIT_MASKDELAY(0xF8F00200, 1),
	EMIT_MASKWRITE(0xE000A008, 0xFFFFFFFFU, 0xBFFF4000U),
	EMIT_EXIT(),
};

unsigned long ps7_post_config_3_0[] = {
	EMIT_WRITE(0xF8000008, 0x0000DF0DU),
	EMIT_MASKWRITE(0xF8000900, 0x0000000FU, 0x0000000FU),
	EMIT_MASKWRITE(0xF8000240, 0xFFFFFFFFU, 0x00000000U),
	EMIT_WRITE(0xF8000004, 0x0000767BU),
	EMIT_EXIT(),
};

unsigned long ps7_debug_3_0[] = {
	// START: top
	// .. START: CROSS TRIGGER CONFIGURATIONS
	// .. .. START: UNLOCKING CTI REGISTERS
	// .. .. KEY = 0XC5ACCE55
	// .. .. ==> 0XF8898FB0[31:0] = 0xC5ACCE55U
	// .. ..     ==> MASK : 0xFFFFFFFFU    VAL : 0xC5ACCE55U
	// .. ..
	EMIT_WRITE(0XF8898FB0, 0xC5ACCE55U),
	// .. .. KEY = 0XC5ACCE55
	// .. .. ==> 0XF8899FB0[31:0] = 0xC5ACCE55U
	// .. ..     ==> MASK : 0xFFFFFFFFU    VAL : 0xC5ACCE55U
	// .. ..
	EMIT_WRITE(0XF8899FB0, 0xC5ACCE55U),
	// .. .. KEY = 0XC5ACCE55
	// .. .. ==> 0XF8809FB0[31:0] = 0xC5ACCE55U
	// .. ..     ==> MASK : 0xFFFFFFFFU    VAL : 0xC5ACCE55U
	// .. ..
	EMIT_WRITE(0XF8809FB0, 0xC5ACCE55U),
	// .. .. FINISH: UNLOCKING CTI REGISTERS
	// .. .. START: ENABLING CTI MODULES AND CHANNELS
	// .. .. FINISH: ENABLING CTI MODULES AND CHANNELS
	// .. .. START: MAPPING CPU0, CPU1 AND FTM EVENTS TO CTM CHANNELS
	// .. .. FINISH: MAPPING CPU0, CPU1 AND FTM EVENTS TO CTM CHANNELS
	// .. FINISH: CROSS TRIGGER CONFIGURATIONS
	// FINISH: top
	//
	EMIT_EXIT(),

	//
};

unsigned long
ps7GetSiliconVersion () {
  // Read PS version from MCTRL register [31:28]
  unsigned long mask = 0xF0000000;
  unsigned long *addr = (unsigned long*) 0XF8007080;
  unsigned long ps_version = (*addr & mask) >> 28;
  return ps_version;
}

void mask_write (unsigned long add , unsigned long  mask, unsigned long val ) {
		volatile unsigned long *addr = (volatile unsigned long*) add;
		*addr = ( val & mask ) | ( *addr & ~mask);
		//xil_printf("MaskWrite : 0x%x--> 0x%x \n \r" ,add, *addr);
}


int mask_poll(unsigned long add , unsigned long mask ) {
		volatile unsigned long *addr = (volatile unsigned long*) add;
		int i = 0;
		while (!(*addr & mask)) {
		  if (i == PS7_MASK_POLL_TIME) {
			return -1;
		  }
		  i++;
		}
	 return 1;
		//xil_printf("MaskPoll : 0x%x --> 0x%x \n \r" , add, *addr);
}

unsigned long mask_read(unsigned long add , unsigned long mask ) {
		volatile unsigned long *addr = (volatile unsigned long*) add;
		unsigned long val = (*addr & mask);
		//xil_printf("MaskRead : 0x%x --> 0x%x \n \r" , add, val);
		return val;
}



int
ps7_config(unsigned long * ps7_config_init)
{
	unsigned long *ptr = ps7_config_init;

	unsigned long  opcode;            // current instruction ..
	unsigned long  args[16];           // no opcode has so many args ...
	int  numargs;           // number of arguments of this instruction
	int  j;                 // general purpose index

	volatile unsigned long *addr;         // some variable to make code readable
	unsigned long  val,mask;              // some variable to make code readable

	int finish = -1 ;           // loop while this is negative !
	int i = 0;                  // Timeout variable

	while( finish < 0 ) {
		numargs = ptr[0] & 0xF;
		opcode = ptr[0] >> 4;

		for( j = 0 ; j < numargs ; j ++ )
			args[j] = ptr[j+1];
		ptr += numargs + 1;


		switch ( opcode ) {

		case OPCODE_EXIT:
			finish = PS7_INIT_SUCCESS;
			break;

		case OPCODE_CLEAR:
			addr = (unsigned long*) args[0];
			*addr = 0;
			break;

		case OPCODE_WRITE:
			addr = (unsigned long*) args[0];
			val = args[1];
			*addr = val;
			break;

		case OPCODE_MASKWRITE:
			addr = (unsigned long*) args[0];
			mask = args[1];
			val = args[2];
			*addr = ( val & mask ) | ( *addr & ~mask);
			break;

		case OPCODE_MASKPOLL:
			addr = (unsigned long*) args[0];
			mask = args[1];
			i = 0;
			while (!(*addr & mask)) {
				if (i == PS7_MASK_POLL_TIME) {
					finish = PS7_INIT_TIMEOUT;
					break;
				}
				i++;
			}
			break;
		case OPCODE_MASKDELAY:
			addr = (unsigned long*) args[0];
			mask = args[1];
			int delay = get_number_of_cycles_for_delay(mask);
			perf_reset_and_start_timer();
			while ((*addr < delay)) {
			}
			break;
		default:
			finish = PS7_INIT_CORRUPT;
			break;
		}
	}
	return finish;
}

/*
 * Real Zybo Z7-20 hardware is always silicon version 3 -- the version-1/2
 * tables and runtime ps7GetSiliconVersion() branching that Xilinx's own
 * ps7_init.c normally carries were removed entirely (not just left
 * unused): the FSBL runs from a few hundred KB of on-chip RAM, and the
 * removed tables alone were several hundred KB of dead .rodata that
 * overflowed it. ps7_ddr_init_data_3_0 was also trimmed to a no-op --
 * this design doesn't use DDR (see NODDR in ../../sw/build.sh).
 */
unsigned long *ps7_mio_init_data = ps7_mio_init_data_3_0;
unsigned long *ps7_pll_init_data = ps7_pll_init_data_3_0;
unsigned long *ps7_clock_init_data = ps7_clock_init_data_3_0;
unsigned long *ps7_ddr_init_data = ps7_ddr_init_data_3_0;
unsigned long *ps7_peripherals_init_data = ps7_peripherals_init_data_3_0;

int
ps7_post_config()
{
  return ps7_config (ps7_post_config_3_0);
}

int
ps7_debug()
{
  return ps7_config (ps7_debug_3_0);
}

int
ps7_init()
{
  int ret;

  // MIO init
  ret = ps7_config (ps7_mio_init_data);
  if (ret != PS7_INIT_SUCCESS) return ret;

  // PLL init
  ret = ps7_config (ps7_pll_init_data);
  if (ret != PS7_INIT_SUCCESS) return ret;

  // Clock init
  ret = ps7_config (ps7_clock_init_data);
  if (ret != PS7_INIT_SUCCESS) return ret;

  // DDR init (no-op -- see comment above)
  ret = ps7_config (ps7_ddr_init_data);
  if (ret != PS7_INIT_SUCCESS) return ret;

  // Peripherals init
  ret = ps7_config (ps7_peripherals_init_data);
  if (ret != PS7_INIT_SUCCESS) return ret;

  return PS7_INIT_SUCCESS;
}




/* For delay calculation using global timer */

/* start timer */
 void perf_start_clock(void)
{
	*(volatile unsigned int*)SCU_GLOBAL_TIMER_CONTROL = ((1 << 0) | // Timer Enable
							  (1 << 3) | // Auto-increment
							  (0 << 8) // Pre-scale
	);
}

/* stop timer and reset timer count regs */
 void perf_reset_clock(void)
{
	perf_disable_clock();
	*(volatile unsigned int*)SCU_GLOBAL_TIMER_COUNT_L32 = 0;
	*(volatile unsigned int*)SCU_GLOBAL_TIMER_COUNT_U32 = 0;
}

/* Compute mask for given delay in milliseconds*/
int get_number_of_cycles_for_delay(unsigned int delay)
{
  // GTC is always clocked at 1/2 of the CPU frequency (CPU_3x2x)
  return (APU_FREQ*delay/(2*1000));

}

/* stop timer */
 void perf_disable_clock(void)
{
	*(volatile unsigned int*)SCU_GLOBAL_TIMER_CONTROL = 0;
}

void perf_reset_and_start_timer()
{
		perf_reset_clock();
		perf_start_clock();
}




